{
    'vegetarian': True, 
    'vegan': True, 
    'glutenFree': True, 
    'dairyFree': True, 
    'veryHealthy': False, 
    'cheap': False, 
    'veryPopular': False, 
    'sustainable': False, 
    'lowFodmap': True, 
    'weightWatcherSmartPoints': 21, 
    'gaps': 'no', 
    'preparationMinutes': -1, 
    'cookingMinutes': -1, 
    'aggregateLikes': 1, 
    'healthScore': 12, 
    'creditsText': 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit', 
    'license': 'CC BY 3.0', 
    'sourceName': 'Foodista', 
    'pricePerServing': 130.92, 
        'id': 639794, 
        'title': 'Coconut milk risotto (Arborio rice pudding)', 
        'readyInMinutes': 45, 
        'servings': 8, 
        'sourceUrl': 'http://www.foodista.com/recipe/RNYXJNJC/coconut-milk-risotto-arborio-rice-pudding', 
        'image': 'https://spoonacular.com/recipeImages/639794-556x370.jpg', 
        'imageType': 'jpg', 
        'nutrition': 
            {
                'nutrients': 
                    [
                        {'name': 'Calories', 'amount': 755.05, 'unit': 'kcal', 'percentOfDailyNeeds': 37.75}, 
                    {'name': 'Fat', 'amount': 25.62, 'unit': 'g', 'percentOfDailyNeeds': 39.42}, 
                    {'name': 'Saturated Fat', 'amount': 22.3, 'unit': 'g', 'percentOfDailyNeeds': 139.38}, 
                    {'name': 'Carbohydrates', 'amount': 122.57, 'unit': 'g', 'percentOfDailyNeeds': 40.86}, 
                    {'name': 'Net Carbohydrates', 'amount': 117.47, 'unit': 'g', 'percentOfDailyNeeds': 42.72}, 
                    {'name': 'Sugar', 'amount': 18.0, 'unit': 'g', 'percentOfDailyNeeds': 20.0}, 
                    {'name': 'Cholesterol', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 0.0}, 
                    {'name': 'Sodium', 'amount': 21.83, 'unit': 'mg', 'percentOfDailyNeeds': 0.95}, 
                    {'name': 'Protein', 'amount': 10.62, 'unit': 'g', 'percentOfDailyNeeds': 21.23}, 
                    {'name': 'Manganese', 'amount': 2.67, 'unit': 'mg', 'percentOfDailyNeeds': 133.37}, 
                    {'name': 'Folate', 'amount': 305.56, 'unit': 'µg', 'percentOfDailyNeeds': 76.39}, 
                    {'name': 'Iron', 'amount': 9.42, 'unit': 'mg', 'percentOfDailyNeeds': 52.35}, 
                    {'name': 'Vitamin B1', 'amount': 0.73, 'unit': 'mg', 'percentOfDailyNeeds': 48.89}, 
                    {'name': 'Vitamin B3', 'amount': 5.93, 'unit': 'mg', 'percentOfDailyNeeds': 29.65}, 
                    {'name': 'Selenium', 'amount': 19.43, 'unit': 'µg', 'percentOfDailyNeeds': 27.75}, 
                    {'name': 'Copper', 'amount': 0.54, 'unit': 'mg', 'percentOfDailyNeeds': 27.14}, 
                    {'name': 'Phosphorus', 'amount': 232.45, 'unit': 'mg', 'percentOfDailyNeeds': 23.25}, 
                    {'name': 'Magnesium', 'amount': 84.74, 'unit': 'mg', 'percentOfDailyNeeds': 21.18}, 
                    {'name': 'Fiber', 'amount': 5.11, 'unit': 'g', 'percentOfDailyNeeds': 20.42}, 
                    {'name': 'Vitamin B5', 'amount': 1.82, 'unit': 'mg', 'percentOfDailyNeeds': 18.23}, 
                    {'name': 'Zinc', 'amount': 2.09, 'unit': 'mg', 'percentOfDailyNeeds': 13.92}, 
                    {'name': 'Vitamin B6', 'amount': 0.26, 'unit': 'mg', 'percentOfDailyNeeds': 12.92}, 
                    {'name': 'Potassium', 'amount': 388.09, 'unit': 'mg', 'percentOfDailyNeeds': 11.09}, 
                    {'name': 'Calcium', 'amount': 65.71, 'unit': 'mg', 'percentOfDailyNeeds': 6.57}, 
                    {'name': 'Vitamin B2', 'amount': 0.06, 'unit': 'mg', 'percentOfDailyNeeds': 3.62}, 
                    {'name': 'Vitamin C', 'amount': 1.31, 'unit': 'mg', 'percentOfDailyNeeds': 1.59}], 'properties': [
                        {'name': 'Glycemic Index', 'amount': 34.5, 'unit': ''}, 
                    {'name': 'Glycemic Load', 'amount': 81.39, 'unit': ''}, 
                    {'name': 'Inflammation Score', 'amount': -6.0, 'unit': ''}, 
                    {'name': 'Nutrition Score', 'amount': 21.579565217391302, 'unit': '%'}], 'flavonoids': [
                        {'name': 'Cyanidin', 'amount': 0.0, 'unit': ''}, 
                    {'name': 'Petunidin', 'amount': 0.0, 'unit': ''}, 
                    {'name': 'Delphinidin', 'amount': 0.0, 'unit': ''}, 
                    {'name': 'Malvidin', 'amount': 0.0, 'unit': ''}, 
                    {'name': 'Pelargonidin', 'amount': 0.0, 'unit': ''}, 
                    {'name': 'Peonidin', 'amount': 0.0, 'unit': ''}, 
                    {'name': 'Catechin', 'amount': 0.0, 'unit': ''}, 
                    {'name': 'Epigallocatechin', 'amount': 0.0, 'unit': ''}, 
                    {'name': 'Epicatechin', 'amount': 0.0, 'unit': ''}, 
                    {'name': 'Epicatechin 3-gallate', 'amount': 0.0, 'unit': ''}, 
                    {'name': 'Epigallocatechin 3-gallate', 'amount': 0.0, 'unit': ''}, 
                    {'name': 'Theaflavin', 'amount': 0.0, 'unit': ''}, 
                    {'name': 'Thearubigins', 'amount': 0.0, 'unit': ''}, 
                    {'name': 'Eriodictyol', 'amount': 0.0, 'unit': ''}, 
                    {'name': 'Hesperetin', 'amount': 0.0, 'unit': ''}, 
                    {'name': 'Naringenin', 'amount': 0.0, 'unit': ''}, 
                    {'name': 'Apigenin', 'amount': 0.0, 'unit': ''}, 
                    {'name': 'Luteolin', 'amount': 0.0, 'unit': ''}, 
                    {'name': 'Isorhamnetin', 'amount': 0.0, 'unit': ''}, 
                    {'name': 'Kaempferol', 'amount': 0.0, 'unit': ''}, 
                    {'name': 'Myricetin', 'amount': 0.0, 'unit': ''}, 
                    {'name': 'Quercetin', 'amount': 0.0, 'unit': ''}, 
                    {'name': "Theaflavin-3,3'-digallate", 'amount': 0.0, 'unit': ''}, 
                    {'name': "Theaflavin-3'-gallate", 'amount': 0.0, 'unit': ''}, 
                    {'name': 'Theaflavin-3-gallate', 'amount': 0.0, 'unit': ''}, 
                    {'name': 'Gallocatechin', 'amount': 0.0, 'unit': ''}], 'ingredients': [
                        {'id': 10020052, 'name': 'arborio rice', 'amount': 0.31, 'unit': 'cups', 'nutrients': [
                        {'name': 'Net Carbohydrates', 'amount': 47.72, 'unit': 'g', 'percentOfDailyNeeds': 42.72}, 
                    {'name': 'Vitamin C', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 1.59}, 
                    {'name': 'Vitamin B5', 'amount': 0.8, 'unit': 'mg', 'percentOfDailyNeeds': 18.23}, 
                    {'name': 'Copper', 'amount': 0.13, 'unit': 'mg', 'percentOfDailyNeeds': 27.14}, 
                    {'name': 'Poly Unsaturated Fat', 'amount': 0.09, 'unit': 'g', 'percentOfDailyNeeds': 0.0}, 
                    {'name': 'Saturated Fat', 'amount': 0.09, 'unit': 'g', 'percentOfDailyNeeds': 139.38}, 
                    {'name': 'Cholesterol', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 0.0}, 
                    {'name': 'Vitamin B12', 'amount': 0.0, 'unit': 'µg', 'percentOfDailyNeeds': 0.0}, 
                    {'name': 'Carbohydrates', 'amount': 49.47, 'unit': 'g', 'percentOfDailyNeeds': 40.86}, 
                    {'name': 'Folic Acid', 'amount': 140.63, 'unit': 'µg', 'percentOfDailyNeeds': 0.0}, 
                    {'name': 'Phosphorus', 'amount': 59.38, 'unit': 'mg', 'percentOfDailyNeeds': 23.25}, 
                    {'name': 'Vitamin B3', 'amount': 2.57, 'unit': 'mg', 'percentOfDailyNeeds': 29.65}, 
                    {'name': 'Vitamin B6', 'amount': 0.11, 'unit': 'mg', 'percentOfDailyNeeds': 12.92}, 
                    {'name': 'Iron', 'amount': 2.64, 'unit': 'mg', 'percentOfDailyNeeds': 52.35}, 
                    {'name': 'Magnesium', 'amount': 14.38, 'unit': 'mg', 'percentOfDailyNeeds': 21.18}, 
                    {'name': 'Vitamin B2', 'amount': 0.03, 'unit': 'mg', 'percentOfDailyNeeds': 3.62}, 
                    {'name': 'Fiber', 'amount': 1.75, 'unit': 'g', 'percentOfDailyNeeds': 20.42}, 
                    {'name': 'Zinc', 'amount': 0.69, 'unit': 'mg', 'percentOfDailyNeeds': 13.92}, 
                    {'name': 'Selenium', 'amount': 9.44, 'unit': 'µg', 'percentOfDailyNeeds': 27.75}, 
                    {'name': 'Potassium', 'amount': 47.5, 'unit': 'mg', 'percentOfDailyNeeds': 11.09}, 
                    {'name': 'Fat', 'amount': 0.32, 'unit': 'g', 'percentOfDailyNeeds': 39.42}, 
                    {'name': 'Vitamin B1', 'amount': 0.35, 'unit': 'mg', 'percentOfDailyNeeds': 48.89}, 
                    {'name': 'Folate', 'amount': 144.38, 'unit': 'µg', 'percentOfDailyNeeds': 76.39}, 
                    {'name': 'Manganese', 'amount': 0.65, 'unit': 'mg', 'percentOfDailyNeeds': 133.37}, 
                    {'name': 'Sodium', 'amount': 0.63, 'unit': 'mg', 'percentOfDailyNeeds': 0.95}, 
                    {'name': 'Mono Unsaturated Fat', 'amount': 0.1, 'unit': 'g', 'percentOfDailyNeeds': 0.0}, 
                    {'name': 'Protein', 'amount': 4.06, 'unit': 'g', 'percentOfDailyNeeds': 21.23}, 
                    {'name': 'Vitamin A', 'amount': 0.0, 'unit': 'IU', 'percentOfDailyNeeds': 0.15}, 
                    {'name': 'Calcium', 'amount': 1.88, 'unit': 'mg', 'percentOfDailyNeeds': 6.57}, 
                    {'name': 'Vitamin D', 'amount': 0.0, 'unit': 'µg', 'percentOfDailyNeeds': 0.0}, 
                    {'name': 'Calories', 'amount': 223.75, 'unit': 'kcal', 'percentOfDailyNeeds': 37.75}]}, 
                    {'id': 10020052, 'name': 'arborio rice', 'amount': 0.31, 'unit': 'cups', 'nutrients': [
                        {'name': 'Net Carbohydrates', 'amount': 47.72, 'unit': 'g', 'percentOfDailyNeeds': 42.72}, 
                    {'name': 'Vitamin C', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 1.59}, 
                    {'name': 'Vitamin B5', 'amount': 0.8, 'unit': 'mg', 'percentOfDailyNeeds': 18.23}, 
                    {'name': 'Copper', 'amount': 0.13, 'unit': 'mg', 'percentOfDailyNeeds': 27.14}, 
                    {'name': 'Poly Unsaturated Fat', 'amount': 0.09, 'unit': 'g', 'percentOfDailyNeeds': 0.0}, 
                    {'name': 'Saturated Fat', 'amount': 0.09, 'unit': 'g', 'percentOfDailyNeeds': 139.38}, 
                    {'name': 'Cholesterol', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 0.0}, 
                    {'name': 'Vitamin B12', 'amount': 0.0, 'unit': 'µg', 'percentOfDailyNeeds': 0.0}, 
                    {'name': 'Carbohydrates', 'amount': 49.47, 'unit': 'g', 'percentOfDailyNeeds': 40.86}, 
                    {'name': 'Folic Acid', 'amount': 140.63, 'unit': 'µg', 'percentOfDailyNeeds': 0.0}, 
                    {'name': 'Phosphorus', 'amount': 59.38, 'unit': 'mg', 'percentOfDailyNeeds': 23.25}, 
                    {'name': 'Vitamin B3', 'amount': 2.57, 'unit': 'mg', 'percentOfDailyNeeds': 29.65}, 
                    {'name': 'Vitamin B6', 'amount': 0.11, 'unit': 'mg', 'percentOfDailyNeeds': 12.92}, 
                    {'name': 'Iron', 'amount': 2.64, 'unit': 'mg', 'percentOfDailyNeeds': 52.35}, 
                    {'name': 'Magnesium', 'amount': 14.38, 'unit': 'mg', 'percentOfDailyNeeds': 21.18}, 
                    {'name': 'Vitamin B2', 'amount': 0.03, 'unit': 'mg', 'percentOfDailyNeeds': 3.62}, 
                    {'name': 'Fiber', 'amount': 1.75, 'unit': 'g', 'percentOfDailyNeeds': 20.42}, 
                    {'name': 'Zinc', 'amount': 0.69, 'unit': 'mg', 'percentOfDailyNeeds': 13.92}, 
                    {'name': 'Selenium', 'amount': 9.44, 'unit': 'µg', 'percentOfDailyNeeds': 27.75}, 
                    {'name': 'Potassium', 'amount': 47.5, 'unit': 'mg', 'percentOfDailyNeeds': 11.09}, 
                    {'name': 'Fat', 'amount': 0.32, 'unit': 'g', 'percentOfDailyNeeds': 39.42}, 
                    {'name': 'Vitamin B1', 'amount': 0.35, 'unit': 'mg', 'percentOfDailyNeeds': 48.89}, 
                    {'name': 'Folate', 'amount': 144.38, 'unit': 'µg', 'percentOfDailyNeeds': 76.39}, 
                    {'name': 'Manganese', 'amount': 0.65, 'unit': 'mg', 'percentOfDailyNeeds': 133.37}, 
                    {'name': 'Sodium', 'amount': 0.63, 'unit': 'mg', 'percentOfDailyNeeds': 0.95}, 
                    {'name': 'Mono Unsaturated Fat', 'amount': 0.1, 'unit': 'g', 'percentOfDailyNeeds': 0.0}, 
                    {'name': 'Protein', 'amount': 4.06, 'unit': 'g', 'percentOfDailyNeeds': 21.23}, 
                    {'name': 'Vitamin A', 'amount': 0.0, 'unit': 'IU', 'percentOfDailyNeeds': 0.15}, 
                    {'name': 'Calcium', 'amount': 1.88, 'unit': 'mg', 'percentOfDailyNeeds': 6.57}, 
                    {'name': 'Vitamin D', 'amount': 0.0, 'unit': 'µg', 'percentOfDailyNeeds': 0.0}, 
                    {'name': 'Calories', 'amount': 223.75, 'unit': 'kcal', 'percentOfDailyNeeds': 37.75}]}, 
                    {'id': 19334, 'name': 'brown sugar', 'amount': 0.04, 'unit': 'cup', 'nutrients': [
                        {'name': 'Net Carbohydrates', 'amount': 8.99, 'unit': 'g', 'percentOfDailyNeeds': 42.72}, 
                    {'name': 'Vitamin C', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 1.59}, 
                    {'name': 'Vitamin B5', 'amount': 0.01, 'unit': 'mg', 'percentOfDailyNeeds': 18.23}, 
                    {'name': 'Copper', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 27.14}, 
                    {'name': 'Poly Unsaturated Fat', 'amount': 0.0, 'unit': 'g', 'percentOfDailyNeeds': 0.0}, 
                    {'name': 'Saturated Fat', 'amount': 0.0, 'unit': 'g', 'percentOfDailyNeeds': 139.38}, 
                    {'name': 'Sugar', 'amount': 8.89, 'unit': 'g', 'percentOfDailyNeeds': 20.0}, 
                    {'name': 'Vitamin E', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 0.44}, 
                    {'name': 'Cholesterol', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 0.0}, 
                    {'name': 'Vitamin B12', 'amount': 0.0, 'unit': 'µg', 'percentOfDailyNeeds': 0.0}, 
                    {'name': 'Carbohydrates', 'amount': 8.99, 'unit': 'g', 'percentOfDailyNeeds': 40.86}, 
                    {'name': 'Folic Acid', 'amount': 0.0, 'unit': 'µg', 'percentOfDailyNeeds': 0.0}, 
                    {'name': 'Phosphorus', 'amount': 0.37, 'unit': 'mg', 'percentOfDailyNeeds': 23.25}, 
                    {'name': 'Vitamin B3', 'amount': 0.01, 'unit': 'mg', 'percentOfDailyNeeds': 29.65}, 
                    {'name': 'Vitamin K', 'amount': 0.0, 'unit': 'µg', 'percentOfDailyNeeds': 0.78}, 
                    {'name': 'Vitamin B6', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 12.92}, 
                    {'name': 'Iron', 'amount': 0.07, 'unit': 'mg', 'percentOfDailyNeeds': 52.35}, 
                    {'name': 'Magnesium', 'amount': 0.83, 'unit': 'mg', 'percentOfDailyNeeds': 21.18}, 
                    {'name': 'Vitamin B2', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 3.62}, 
                    {'name': 'Choline', 'amount': 0.21, 'unit': 'mg', 'percentOfDailyNeeds': 0.0}, 
                    {'name': 'Alcohol', 'amount': 0.0, 'unit': 'g', 'percentOfDailyNeeds': 0.0}, 
                    {'name': 'Fiber', 'amount': 0.0, 'unit': 'g', 'percentOfDailyNeeds': 20.42}, 
                    {'name': 'Zinc', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 13.92}, 
                    {'name': 'Selenium', 'amount': 0.11, 'unit': 'µg', 'percentOfDailyNeeds': 27.75}, 
                    {'name': 'Folate', 'amount': 0.09, 'unit': 'µg', 'percentOfDailyNeeds': 76.39}, 
                    {'name': 'Vitamin B1', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 48.89}, 
                    {'name': 'Fat', 'amount': 0.0, 'unit': 'g', 'percentOfDailyNeeds': 39.42}, 
                    {'name': 'Potassium', 'amount': 12.19, 'unit': 'mg', 'percentOfDailyNeeds': 11.09}, 
                    {'name': 'Manganese', 'amount': 0.01, 'unit': 'mg', 'percentOfDailyNeeds': 133.37}, 
                    {'name': 'Sodium', 'amount': 2.57, 'unit': 'mg', 'percentOfDailyNeeds': 0.95}, 
                    {'name': 'Mono Unsaturated Fat', 'amount': 0.0, 'unit': 'g', 'percentOfDailyNeeds': 0.0}, 
                    {'name': 'Protein', 'amount': 0.01, 'unit': 'g', 'percentOfDailyNeeds': 21.23}, 
                    {'name': 'Caffeine', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 0.0}, 
                    {'name': 'Vitamin A', 'amount': 0.0, 'unit': 'IU', 'percentOfDailyNeeds': 0.15}, 
                    {'name': 'Calcium', 'amount': 7.61, 'unit': 'mg', 'percentOfDailyNeeds': 6.57}, 
                    {'name': 'Lycopene', 'amount': 0.0, 'unit': 'µg', 'percentOfDailyNeeds': 0.0}, 
                    {'name': 'Vitamin D', 'amount': 0.0, 'unit': 'µg', 'percentOfDailyNeeds': 0.0}, 
                    {'name': 'Calories', 'amount': 34.83, 'unit': 'kcal', 'percentOfDailyNeeds': 37.75}
                    ]
                    }, 
                    {
                        'id': 19334, 'name': 'brown sugar', 'amount': 0.04, 'unit': 'cup',
                        'nutrients': 
                            [
                                {'name': 'Net Carbohydrates', 'amount': 8.99, 'unit': 'g', 'percentOfDailyNeeds': 42.72}, 
                            {'name': 'Vitamin C', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 1.59}, 
                            {'name': 'Vitamin B5', 'amount': 0.01, 'unit': 'mg', 'percentOfDailyNeeds': 18.23}, 
                            {'name': 'Copper', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 27.14}, 
                            {'name': 'Poly Unsaturated Fat', 'amount': 0.0, 'unit': 'g', 'percentOfDailyNeeds': 0.0}, 
                            {'name': 'Saturated Fat', 'amount': 0.0, 'unit': 'g', 'percentOfDailyNeeds': 139.38}, 
                            {'name': 'Sugar', 'amount': 8.89, 'unit': 'g', 'percentOfDailyNeeds': 20.0}, 
                            {'name': 'Vitamin E', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 0.44}, 
                            {'name': 'Cholesterol', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 0.0}, 
                            {'name': 'Vitamin B12', 'amount': 0.0, 'unit': 'µg', 'percentOfDailyNeeds': 0.0}, 
                            {'name': 'Carbohydrates', 'amount': 8.99, 'unit': 'g', 'percentOfDailyNeeds': 40.86}, 
                            {'name': 'Folic Acid', 'amount': 0.0, 'unit': 'µg', 'percentOfDailyNeeds': 0.0}, 
                            {'name': 'Phosphorus', 'amount': 0.37, 'unit': 'mg', 'percentOfDailyNeeds': 23.25}, 
                            {'name': 'Vitamin B3', 'amount': 0.01, 'unit': 'mg', 'percentOfDailyNeeds': 29.65}, 
                            {'name': 'Vitamin K', 'amount': 0.0, 'unit': 'µg', 'percentOfDailyNeeds': 0.78}, 
                            {'name': 'Vitamin B6', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 12.92}, 
                            {'name': 'Iron', 'amount': 0.07, 'unit': 'mg', 'percentOfDailyNeeds': 52.35}, 
                            {'name': 'Magnesium', 'amount': 0.83, 'unit': 'mg', 'percentOfDailyNeeds': 21.18}, 
                            {'name': 'Vitamin B2', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 3.62}, 
                            {'name': 'Choline', 'amount': 0.21, 'unit': 'mg', 'percentOfDailyNeeds': 0.0}, 
                            {'name': 'Alcohol', 'amount': 0.0, 'unit': 'g', 'percentOfDailyNeeds': 0.0}, 
                            {'name': 'Fiber', 'amount': 0.0, 'unit': 'g', 'percentOfDailyNeeds': 20.42}, 
                            {'name': 'Zinc', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 13.92}, 
                            {'name': 'Selenium', 'amount': 0.11, 'unit': 'µg', 'percentOfDailyNeeds': 27.75}, 
                            {'name': 'Folate', 'amount': 0.09, 'unit': 'µg', 'percentOfDailyNeeds': 76.39}, 
                            {'name': 'Vitamin B1', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 48.89}, 
                            {'name': 'Fat', 'amount': 0.0, 'unit': 'g', 'percentOfDailyNeeds': 39.42}, 
                            {'name': 'Potassium', 'amount': 12.19, 'unit': 'mg', 'percentOfDailyNeeds': 11.09}, 
                            {'name': 'Manganese', 'amount': 0.01, 'unit': 'mg', 'percentOfDailyNeeds': 133.37}, 
                            {'name': 'Sodium', 'amount': 2.57, 'unit': 'mg', 'percentOfDailyNeeds': 0.95}, 
                            {'name': 'Mono Unsaturated Fat', 'amount': 0.0, 'unit': 'g', 'percentOfDailyNeeds': 0.0}, 
                            {'name': 'Protein', 'amount': 0.01, 'unit': 'g', 'percentOfDailyNeeds': 21.23}, 
                            {'name': 'Caffeine', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 0.0}, 
                            {'name': 'Vitamin A', 'amount': 0.0, 'unit': 'IU', 'percentOfDailyNeeds': 0.15}, 
                            {'name': 'Calcium', 'amount': 7.61, 'unit': 'mg', 'percentOfDailyNeeds': 6.57}, 
                            {'name': 'Lycopene', 'amount': 0.0, 'unit': 'µg', 'percentOfDailyNeeds': 0.0}, 
                            {'name': 'Vitamin D', 'amount': 0.0, 'unit': 'µg', 'percentOfDailyNeeds': 0.0}, 
                            {'name': 'Calories', 'amount': 34.83, 'unit': 'kcal', 'percentOfDailyNeeds': 37.75}
                            ]
                            }, 
                    {'id': 12104, 'name': 'coconut', 'amount': 0.5, 'unit': 'tablespoons', 'nutrients': 
                        [
                            {'name': 'Net Carbohydrates', 'amount': 0.16, 'unit': 'g', 'percentOfDailyNeeds': 42.72}, 
                        {'name': 'Vitamin C', 'amount': 0.08, 'unit': 'mg', 'percentOfDailyNeeds': 1.59}, 
                        {'name': 'Vitamin B5', 'amount': 0.01, 'unit': 'mg', 'percentOfDailyNeeds': 18.23}, 
                        {'name': 'Copper', 'amount': 0.01, 'unit': 'mg', 'percentOfDailyNeeds': 27.14}, 
                        {'name': 'Poly Unsaturated Fat', 'amount': 0.01, 'unit': 'g', 'percentOfDailyNeeds': 0.0}, 
                        {'name': 'Saturated Fat', 'amount': 0.74, 'unit': 'g', 'percentOfDailyNeeds': 139.38}, 
                        {'name': 'Sugar', 'amount': 0.16, 'unit': 'g', 'percentOfDailyNeeds': 20.0}, 
                        {'name': 'Vitamin E', 'amount': 0.01, 'unit': 'mg', 'percentOfDailyNeeds': 0.44}, 
                        {'name': 'Cholesterol', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 0.0}, 
                        {'name': 'Vitamin B12', 'amount': 0.0, 'unit': 'µg', 'percentOfDailyNeeds': 0.0}, 
                        {'name': 'Carbohydrates', 'amount': 0.38, 'unit': 'g', 'percentOfDailyNeeds': 40.86}, 
                        {'name': 'Folic Acid', 'amount': 0.0, 'unit': 'µg', 'percentOfDailyNeeds': 0.0}, 
                        {'name': 'Phosphorus', 'amount': 2.83, 'unit': 'mg', 'percentOfDailyNeeds': 23.25}, 
                        {'name': 'Vitamin B3', 'amount': 0.01, 'unit': 'mg', 'percentOfDailyNeeds': 29.65}, 
                        {'name': 'Vitamin K', 'amount': 0.0, 'unit': 'µg', 'percentOfDailyNeeds': 0.78}, 
                        {'name': 'Vitamin B6', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 12.92}, 
                        {'name': 'Iron', 'amount': 0.06, 'unit': 'mg', 'percentOfDailyNeeds': 52.35}, 
                        {'name': 'Magnesium', 'amount': 0.8, 'unit': 'mg', 'percentOfDailyNeeds': 21.18}, 
                        {'name': 'Vitamin B2', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 3.62}, 
                        {'name': 'Choline', 'amount': 0.3, 'unit': 'mg', 'percentOfDailyNeeds': 0.0}, 
                        {'name': 'Alcohol', 'amount': 0.0, 'unit': 'g', 'percentOfDailyNeeds': 0.0}, 
                        {'name': 'Fiber', 'amount': 0.22, 'unit': 'g', 'percentOfDailyNeeds': 20.42}, 
                        {'name': 'Zinc', 'amount': 0.03, 'unit': 'mg', 'percentOfDailyNeeds': 13.92}, 
                        {'name': 'Selenium', 'amount': 0.25, 'unit': 'µg', 'percentOfDailyNeeds': 27.75}, 
                        {'name': 'Folate', 'amount': 0.65, 'unit': 'µg', 'percentOfDailyNeeds': 76.39}, 
                        {'name': 'Vitamin B1', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 48.89}, 
                        {'name': 'Fat', 'amount': 0.84, 'unit': 'g', 'percentOfDailyNeeds': 39.42}, 
                        {'name': 'Potassium', 'amount': 8.9, 'unit': 'mg', 'percentOfDailyNeeds': 11.09}, 
                        {'name': 'Manganese', 'amount': 0.04, 'unit': 'mg', 'percentOfDailyNeeds': 133.37}, 
                        {'name': 'Sodium', 'amount': 0.5, 'unit': 'mg', 'percentOfDailyNeeds': 0.95}, 
                        {'name': 'Mono Unsaturated Fat', 'amount': 0.04, 'unit': 'g', 'percentOfDailyNeeds': 0.0}, 
                        {'name': 'Protein', 'amount': 0.08, 'unit': 'g', 'percentOfDailyNeeds': 21.23}, 
                        {'name': 'Caffeine', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 0.0}, 
                        {'name': 'Vitamin A', 'amount': 0.0, 'unit': 'IU', 'percentOfDailyNeeds': 0.15}, 
                        {'name': 'Calcium', 'amount': 0.35, 'unit': 'mg', 'percentOfDailyNeeds': 6.57}, 
                        {'name': 'Lycopene', 'amount': 0.0, 'unit': 'µg', 'percentOfDailyNeeds': 0.0}, 
                        {'name': 'Vitamin D', 'amount': 0.0, 'unit': 'µg', 'percentOfDailyNeeds': 0.0}, 
                        {'name': 'Calories', 'amount': 8.85, 'unit': 'kcal', 'percentOfDailyNeeds': 37.75}]}, 
                    {'id': 12118, 'name': 'coconut milk', 'amount': 0.5, 'unit': 'cups', 'nutrients': [
                        {'name': 'Net Carbohydrates', 'amount': 3.18, 'unit': 'g', 'percentOfDailyNeeds': 42.72}, 
                        {'name': 'Vitamin C', 'amount': 1.13, 'unit': 'mg', 'percentOfDailyNeeds': 1.59}, 
                        {'name': 'Vitamin B5', 'amount': 0.17, 'unit': 'mg', 'percentOfDailyNeeds': 18.23}, 
                        {'name': 'Copper', 'amount': 0.25, 'unit': 'mg', 'percentOfDailyNeeds': 27.14}, 
                        {'name': 'Poly Unsaturated Fat', 'amount': 0.26, 'unit': 'g', 'percentOfDailyNeeds': 0.0}, 
                        {'name': 'Saturated Fat', 'amount': 21.37, 'unit': 'g', 'percentOfDailyNeeds': 139.38}, 
                        {'name': 'Cholesterol', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 0.0}, 
                        {'name': 'Vitamin B12', 'amount': 0.0, 'unit': 'µg', 'percentOfDailyNeeds': 0.0}, 
                        {'name': 'Carbohydrates', 'amount': 3.18, 'unit': 'g', 'percentOfDailyNeeds': 40.86}, 
                        {'name': 'Folic Acid', 'amount': 0.0, 'unit': 'µg', 'percentOfDailyNeeds': 0.0}, 
                        {'name': 'Phosphorus', 'amount': 108.48, 'unit': 'mg', 'percentOfDailyNeeds': 23.25}, 
                        {'name': 'Vitamin B3', 'amount': 0.72, 'unit': 'mg', 'percentOfDailyNeeds': 29.65}, 
                        {'name': 'Vitamin B6', 'amount': 0.03, 'unit': 'mg', 'percentOfDailyNeeds': 12.92}, 
                        {'name': 'Iron', 'amount': 3.73, 'unit': 'mg', 'percentOfDailyNeeds': 52.35}, 
                        {'name': 'Magnesium', 'amount': 51.98, 'unit': 'mg', 'percentOfDailyNeeds': 21.18}, 
                        {'name': 'Vitamin B2', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 3.62}, 
                        {'name': 'Choline', 'amount': 9.6, 'unit': 'mg', 'percentOfDailyNeeds': 0.0}, 
                        {'name': 'Zinc', 'amount': 0.63, 'unit': 'mg', 'percentOfDailyNeeds': 13.92}, 
                        {'name': 'Potassium', 'amount': 248.6, 'unit': 'mg', 'percentOfDailyNeeds': 11.09}, 
                        {'name': 'Fat', 'amount': 24.1, 'unit': 'g', 'percentOfDailyNeeds': 39.42}, 
                        {'name': 'Vitamin B1', 'amount': 0.02, 'unit': 'mg', 'percentOfDailyNeeds': 48.89}, 
                        {'name': 'Folate', 'amount': 15.82, 'unit': 'µg', 'percentOfDailyNeeds': 76.39}, 
                        {'name': 'Manganese', 'amount': 0.87, 'unit': 'mg', 'percentOfDailyNeeds': 133.37}, 
                        {'name': 'Sodium', 'amount': 14.69, 'unit': 'mg', 'percentOfDailyNeeds': 0.95}, 
                        {'name': 'Mono Unsaturated Fat', 'amount': 1.02, 'unit': 'g', 'percentOfDailyNeeds': 0.0}, 
                        {'name': 'Protein', 'amount': 2.28, 'unit': 'g', 'percentOfDailyNeeds': 21.23}, 
                        {'name': 'Vitamin A', 'amount': 0.0, 'unit': 'IU', 'percentOfDailyNeeds': 0.15}, 
                        {'name': 'Calcium', 'amount': 20.34, 'unit': 'mg', 'percentOfDailyNeeds': 6.57}, 
                        {'name': 'Vitamin D', 'amount': 0.0, 'unit': 'µg', 'percentOfDailyNeeds': 0.0}, 
                        {'name': 'Calories', 'amount': 222.61, 'unit': 'kcal', 'percentOfDailyNeeds': 37.75}]}, 
                    {'id': 1012010, 'name': 'ground cinnamon', 'amount': 1.0, 'unit': 'tsp', 'nutrients': [
                        {'name': 'Net Carbohydrates', 'amount': 0.71, 'unit': 'g', 'percentOfDailyNeeds': 42.72}, 
                        {'name': 'Vitamin C', 'amount': 0.1, 'unit': 'mg', 'percentOfDailyNeeds': 1.59}, 
                        {'name': 'Poly Unsaturated Fat', 'amount': 0.0, 'unit': 'g', 'percentOfDailyNeeds': 0.0}, 
                        {'name': 'Vitamin B5', 'amount': 0.01, 'unit': 'mg', 'percentOfDailyNeeds': 18.23}, 
                        {'name': 'Copper', 'amount': 0.01, 'unit': 'mg', 'percentOfDailyNeeds': 27.14}, 
                        {'name': 'Saturated Fat', 'amount': 0.01, 'unit': 'g', 'percentOfDailyNeeds': 139.38}, 
                        {'name': 'Trans Fat', 'amount': 0.0, 'unit': 'g', 'percentOfDailyNeeds': 0.0}, 
                        {'name': 'Sugar', 'amount': 0.06, 'unit': 'g', 'percentOfDailyNeeds': 20.0}, 
                        {'name': 'Vitamin E', 'amount': 0.06, 'unit': 'mg', 'percentOfDailyNeeds': 0.44}, 
                        {'name': 'Cholesterol', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 0.0}, 
                        {'name': 'Vitamin B12', 'amount': 0.0, 'unit': 'µg', 'percentOfDailyNeeds': 0.0}, 
                        {'name': 'Carbohydrates', 'amount': 2.1, 'unit': 'g', 'percentOfDailyNeeds': 40.86}, 
                        {'name': 'Folic Acid', 'amount': 0.0, 'unit': 'µg', 'percentOfDailyNeeds': 0.0}, 
                        {'name': 'Phosphorus', 'amount': 1.66, 'unit': 'mg', 'percentOfDailyNeeds': 23.25}, 
                        {'name': 'Vitamin B3', 'amount': 0.03, 'unit': 'mg', 'percentOfDailyNeeds': 29.65}, 
                        {'name': 'Vitamin K', 'amount': 0.81, 'unit': 'µg', 'percentOfDailyNeeds': 0.78}, 
                        {'name': 'Vitamin B6', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 12.92}, 
                        {'name': 'Iron', 'amount': 0.22, 'unit': 'mg', 'percentOfDailyNeeds': 52.35}, 
                        {'name': 'Magnesium', 'amount': 1.56, 'unit': 'mg', 'percentOfDailyNeeds': 21.18}, 
                        {'name': 'Vitamin B2', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 3.62}, 
                        {'name': 'Choline', 'amount': 0.29, 'unit': 'mg', 'percentOfDailyNeeds': 0.0}, 
                        {'name': 'Alcohol', 'amount': 0.0, 'unit': 'g', 'percentOfDailyNeeds': 0.0}, 
                        {'name': 'Fiber', 'amount': 1.38, 'unit': 'g', 'percentOfDailyNeeds': 20.42}, 
                        {'name': 'Zinc', 'amount': 0.05, 'unit': 'mg', 'percentOfDailyNeeds': 13.92}, 
                        {'name': 'Selenium', 'amount': 0.08, 'unit': 'µg', 'percentOfDailyNeeds': 27.75}, 
                        {'name': 'Folate', 'amount': 0.16, 'unit': 'µg', 'percentOfDailyNeeds': 76.39}, 
                        {'name': 'Vitamin B1', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 48.89}, 
                        {'name': 'Fat', 'amount': 0.03, 'unit': 'g', 'percentOfDailyNeeds': 39.42}, 
                        {'name': 'Potassium', 'amount': 11.21, 'unit': 'mg', 'percentOfDailyNeeds': 11.09}, 
                        {'name': 'Manganese', 'amount': 0.45, 'unit': 'mg', 'percentOfDailyNeeds': 133.37}, 
                        {'name': 'Sodium', 'amount': 0.26, 'unit': 'mg', 'percentOfDailyNeeds': 0.95}, 
                        {'name': 'Mono Unsaturated Fat', 'amount': 0.01, 'unit': 'g', 'percentOfDailyNeeds': 0.0}, 
                        {'name': 'Protein', 'amount': 0.1, 'unit': 'g', 'percentOfDailyNeeds': 21.23}, 
                        {'name': 'Caffeine', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 0.0}, 
                        {'name': 'Vitamin A', 'amount': 7.67, 'unit': 'IU', 'percentOfDailyNeeds': 0.15}, 
                        {'name': 'Calcium', 'amount': 26.05, 'unit': 'mg', 'percentOfDailyNeeds': 6.57}, 
                        {'name': 'Lycopene', 'amount': 0.39, 'unit': 'µg', 'percentOfDailyNeeds': 0.0}, 
                        {'name': 'Vitamin D', 'amount': 0.0, 'unit': 'µg', 'percentOfDailyNeeds': 0.0}, 
                        {'name': 'Calories', 'amount': 6.42, 'unit': 'kcal', 'percentOfDailyNeeds': 37.75}]}, 
                    {'id': 93812, 'name': 'vanilla powder', 'amount': 0.03, 'unit': 'teaspoon', 'nutrients': [
                        {'name': 'Net Carbohydrates', 'amount': 0.0, 'unit': 'g', 'percentOfDailyNeeds': 42.72}, 
                        {'name': 'Vitamin C', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 1.59}, 
                        {'name': 'Poly Unsaturated Fat', 'amount': 0.0, 'unit': 'g', 'percentOfDailyNeeds': 0.0}, 
                        {'name': 'Vitamin B5', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 18.23}, 
                        {'name': 'Copper', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 27.14}, 
                        {'name': 'Saturated Fat', 'amount': 0.0, 'unit': 'g', 'percentOfDailyNeeds': 139.38}, 
                        {'name': 'Trans Fat', 'amount': 0.0, 'unit': 'g', 'percentOfDailyNeeds': 0.0}, 
                        {'name': 'Sugar', 'amount': 0.0, 'unit': 'g', 'percentOfDailyNeeds': 20.0}, 
                        {'name': 'Vitamin E', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 0.44}, 
                        {'name': 'Cholesterol', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 0.0}, 
                        {'name': 'Vitamin B12', 'amount': 0.0, 'unit': 'µg', 'percentOfDailyNeeds': 0.0}, 
                        {'name': 'Carbohydrates', 'amount': 0.0, 'unit': 'g', 'percentOfDailyNeeds': 40.86}, 
                        {'name': 'Fluoride', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 0.0}, 
                        {'name': 'Phosphorus', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 23.25}, 
                        {'name': 'Vitamin B3', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 29.65}, 
                        {'name': 'Vitamin K', 'amount': 0.0, 'unit': 'µg', 'percentOfDailyNeeds': 0.78}, 
                        {'name': 'Vitamin B6', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 12.92}, 
                        {'name': 'Iron', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 52.35}, 
                        {'name': 'Magnesium', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 21.18}, 
                        {'name': 'Vitamin B2', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 3.62}, 
                        {'name': 'Alcohol', 'amount': 0.0, 'unit': 'g', 'percentOfDailyNeeds': 0.0}, 
                        {'name': 'Fiber', 'amount': 0.0, 'unit': 'g', 'percentOfDailyNeeds': 20.42}, 
                        {'name': 'Zinc', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 13.92}, 
                        {'name': 'Selenium', 'amount': 0.0, 'unit': 'µg', 'percentOfDailyNeeds': 27.75}, 
                        {'name': 'Folate', 'amount': 0.0, 'unit': 'µg', 'percentOfDailyNeeds': 76.39}, 
                        {'name': 'Vitamin B1', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 48.89}, 
                        {'name': 'Fat', 'amount': 0.0, 'unit': 'g', 'percentOfDailyNeeds': 39.42}, 
                        {'name': 'Potassium', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 11.09}, 
                        {'name': 'Manganese', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 133.37}, 
                        {'name': 'Sodium', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 0.95}, 
                        {'name': 'Mono Unsaturated Fat', 'amount': 0.0, 'unit': 'g', 'percentOfDailyNeeds': 0.0}, 
                        {'name': 'Protein', 'amount': 0.0, 'unit': 'g', 'percentOfDailyNeeds': 21.23}, 
                        {'name': 'Caffeine', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 0.0}, 
                        {'name': 'Vitamin A', 'amount': 0.0, 'unit': 'IU', 'percentOfDailyNeeds': 0.15}, 
                        {'name': 'Calcium', 'amount': 0.0, 'unit': 'mg', 'percentOfDailyNeeds': 6.57}, 
                        {'name': 'Vitamin D', 'amount': 0.0, 'unit': 'µg', 'percentOfDailyNeeds': 0.0}, 
                        {'name': 'Calories', 'amount': 0.0, 'unit': 'kcal', 'percentOfDailyNeeds': 37.75}]}], 
                    'caloricBreakdown': 
                        
                        {
                            'percentProtein': 5.56, 
                            'percentFat': 30.21, 
                            'percentCarbs': 64.23
                            }, 
                        'weightPerServing': 
                            {
                                'amount': 261, 'unit': 'g'
                                }
                            }, 
            'summary': 'The recipe Coconut milk risotto (Arborio rice pudding) is ready <b>in about 45 minutes</b> and is definitely an amazing <b>gluten free, dairy free, lacto ovo vegetarian, and fodmap friendly</b> option for lovers of Mediterranean food. This recipe serves 8. One portion of this dish contains about <b>7g of protein</b>, <b>25g of fat</b>, and a total of <b>496 calories</b>. For <b>$1.31 per serving</b>, this recipe <b>covers 14%</b> of your daily requirements of vitamins and minerals. If you have arborio rice, coconut milk, coconut, and a few other ingredients on hand, you can make it. It is brought to you by Foodista. This recipe is liked by 1 foodies and cooks. It works well as a hor d\'oeuvre. Overall, this recipe earns a <b>solid spoonacular score of 52%</b>. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/dairy-free-dessert-risotto-arborio-rice-pudding-1763557">Dairy-Free Dessert Risotto (Arborio Rice Pudding)</a>, <a href="https://spoonacular.com/recipes/coconut-arborio-rice-pudding-54135">Coconut Arborio Rice Pudding</a>, and <a href="https://spoonacular.com/recipes/mushrooom-thyme-risotto-also-known-as-arborio-rice-113975">Mushrooom Thyme Risotto Also Known As Arborio Rice</a>.', 
            'cuisines': ['Mediterranean', 'Italian', 'European'], 
            'dishTypes': ['side dish', 'antipasti', 'starter', 'snack', 'appetizer', 'antipasto', "hor d'oeuvre"], 
            'diets': ['gluten free', 'dairy free', 'lacto ovo vegetarian', 'fodmap friendly', 'vegan'], 
            'occasions': [], 
            'winePairing': {'pairedWines': ['chianti', 'verdicchio', 'trebbiano'], 
                            'pairingText': 'Risotto can be paired with Chianti, Verdicchio, and Trebbiano. Italians know food and they know wine. Trebbiano and Verdicchio are Italian white wines that pair well with fish and white meat, while Chianti is a great Italian red for heavier, bolder dishes. The Santa Margherita Chianti Classico Riserva with a 4.8 out of 5 star rating seems like a good match. It costs about 27 dollars per bottle.', 'productMatches': [{'id': 436659, 'title': 'Santa Margherita Chianti Classico Riserva', 'description': 'The aromas of this complex red wine range from cherries and plums to gladiolus flowers and earthy flint. The tannic, oak-aged flavors are bright and round, with a dry, warm, earthy finish. Recommended for barbecued meat, like sliced Chianina steak, or with game, such as pheasant stuffed with truffles. It is also excellent with mature cheese.', 'price': '$26.989999771118164', 'imageUrl': 'https://spoonacular.com/productImages/436659-312x231.jpg', 'averageRating': 0.9599999785423279, 'ratingCount': 8.0, 'score': 0.9199999785423278, 'link': 'https://click.linksynergy.com/deeplink?id=*QCiIS6t4gA&mid=2025&murl=https%3A%2F%2Fwww.wine.com%2Fproduct%2Fsanta-margherita-chianti-classico-riserva-2013%2F167314'}]}, 'instructions': '<ol><li>In a large saucepan, combine all the ingredients and bring to a boil.</li><li>Simmer over moderate heat, stirring frequently, until the rice is tender and the sauce is thick and creamy, about 30-40 minutes.</li><li>Let cool slightly.</li><li>Spoon the risotto into bowls, garnish with toasted coconut or cinnamon, and serve.</li></ol>', 'analyzedInstructions': [{'name': '', 'steps': [{'number': 1, 'step': 'In a large saucepan, combine all the ingredients and bring to a boil.Simmer over moderate heat, stirring frequently, until the rice is tender and the sauce is thick and creamy, about 30-40 minutes.', 'ingredients': [{'id': 0, 'name': 'sauce', 'localizedName': 'sauce', 'image': ''}, {'id': 20444, 'name': 'rice', 'localizedName': 'rice', 'image': 'uncooked-white-rice.png'}], 'equipment': [{'id': 404669, 'name': 'sauce pan', 'localizedName': 'sauce pan', 'image': 'sauce-pan.jpg'}], 'length': {'number': 40, 'unit': 'minutes'}}, {'number': 2, 'step': 'Let cool slightly.Spoon the risotto into bowls, garnish with toasted coconut or cinnamon, and serve.', 'ingredients': [{'id': 2010, 'name': 'cinnamon', 'localizedName': 'cinnamon', 'image': 'cinnamon.jpg'}, {'id': 12104, 'name': 'coconut', 'localizedName': 'coconut', 'image': 'coconut.jpg'}], 'equipment': [{'id': 404783, 'name': 'bowl', 'localizedName': 'bowl', 'image': 'bowl.jpg'}]}]}], 'originalId': None, 'spoonacularScore': 56.04078674316406, 
            'spoonacularSourceUrl': 'https://spoonacular.com/coconut-milk-risotto-arborio-rice-pudding-639794'}